[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npx vite"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200